# Настройки #

sqliteUrl: C:/ProgramData/STAHLWILLE/Sensomaster4/sensomaster4.db

# Путь до базы данных Access
dbUrl: C:/ProgramData/STAHLWILLE/Sensomaster4/Database.accdb

# Имя Таблицы
tableName: TohnichiCEM

# COM порт подключения моментного  ключа
portName: COM4

# Папка с автоматическими отчетами в pdf
StahlwilleReportsUrl: C:/StahlwilleReports
TohnichiReportsUrl: C:/TohnichiReports

# Размер посылки в байтах
bSizeCEM: 31
bSizeSTC2: 15

XMLUrl: C:/zxy
